name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shardIndex: [ 1, 2, 3 ]
        shardTotal: [ 3 ]
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn

    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps

    - name: Build website
      run: yarn build

    - name: Start website
      run: yarn start & sleep 10

    - name: Run Playwright tests
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
